#!/usr/bin/env python
import re
import sys
import os
from os.path import dirname, join

currentdir = os.getcwd()
os.chdir(dirname(__file__))

from pwpeg import Parser, SyntaxError
from niml.niml import block
from niml.printer import NodeVisitor

parser = Parser(block.instanciate(0))

if __name__ == "__main__":
    for fn in sys.argv[1:]:
        f = open(join(currentdir, fn), "r")
        try:
            root = parser.parse(unicode(f.read(), "utf-8"))
            if not root:
                continue
            print(NodeVisitor().visit(root))
        except SyntaxError as e:
            print(e.fullmessage())
        finally:
            f.close()


