#!/usr/bin/env python
import re
import sys
import os
from os.path import dirname, join

currentdir = os.getcwd()
os.chdir(dirname(__file__))

for f in [ "pwilang" ]:
    # Recompilation des fichiers de grammaire.
    res = os.system('if [ "{0}.pwpeg" -nt "{0}.py" ]; then\n    echo "Recompiling {0}..."; pwpeg "{0}.pwpeg" > "{0}.py"\nfi'.format(f))
    if res != 0:
        print(f)
        sys.exit()

from pwpeg import Parser
from pwilang.pwilang import block
from pwilang.printer import NodeVisitor

parser = Parser(block(""))

if __name__ == "__main__":
    for fn in sys.argv[1:]:
        f = open(join(currentdir, fn), "r")
        root = parser.parse(unicode(f.read(), "utf-8"))
        f.close()

        if not root:
            continue
        print(NodeVisitor().visit(root))
